### PR TITLE
Issue #231: Authentication UI

### LINKED ISSUE #231: Improve authentication widget and UI experience
@RyanBard only created a simple authentication component to prove authentication & authorization was working.

Update the client side code to have a production-ready experience wrt auth.

### PR DESCRIPTION
**Pull request by mckoon**
* Removes original sign in/out from sidenav.
* Adds "Sign in" toolbar button.
* Adds account menu with "Sign out" option.
* Hides create program FAB if not admin.
* Hides organization edit and delete buttons if not admin.
* Hides program edit and delete buttons if not admin.
* Adds tests for authenticationService.
* Replaces getEmail with getUser in authenticationService.
* Adds user profile picture button to toolbar.
* Adds auth component tests.

Closes #231

### CODE REVIEW

**Comment by mckoon** [comment]
# Pre-login Screenshots:

* No FAB
* No edit buttons
* No delete buttons

screen shot 2016-10-30 at 6 10 47 pm

screen shot 2016-10-30 at 6 11 20 pm


screen shot 2016-10-30 at 6 11 47 pm

**Comment by mckoon** [comment]
# Post-login Screenshots

screen shot 2016-10-30 at 6 17 30 pm

screen shot 2016-10-30 at 6 17 57 pm

screen shot 2016-10-30 at 6 18 20 pm

**Comment by mckoon** [comment]
# Sign-out button:

screen shot 2016-10-30 at 6 19 51 pm

**Comment by mckoon** [comment]
Running here: https://hmhb-mckoon.herokuapp.com/views/map

**Comment by RyanBard** [comment]
I tested it with an admin and non-admin :+1:

**Pull request merged**
