### PR TITLE
closes Issue 69

### PR DESCRIPTION
**Pull request by jlgettings**
so far so good?

### CODE REVIEW

**Comment by RyanBard** [comment]
Now merge it and watch it deploy to hmhb.herokuapp.com within about 5 minutes.

**Comment by RyanBard** [comment]
Also note that the statuses all get managed automatically (so it moves to the Done column in waffle).

**Comment by RyanBard** [comment]
Yea, since the ticket wasn't a link in the commit message, it didn't automatically move #69 into the done column.  You can just do it manually by dragging it over in waffle.io.

**Comment by RyanBard** [comment]
The changes are visible (in the dev console) on hmhb.herokuapp.com.

**Comment by jlgettings** [comment]
What exactly do I do to set up postgres? Is it something I download?

**Comment by RyanBard** [comment]
Specifics for setting up postgres depend on your OS.

After you get to the point where you can open a postgres shell to your own local db:
your-command-shell> psql postgres
(postgres is the default DB created)

You can run through the steps creating the hmhb_db database and user to access it that the app needs.

Instructions are in the notes-for-code-setup doc in our google drive: https://docs.google.com/document/d/1wq6PauZRmHhMBzZNsOBxOqe0TLNKw4NUMFaEIOhmvCw/edit

Let me know in chat if you need any help.  And feel free to edit the steps in that doc.  I'll eventually put it into a readme.md or contributing.md or something as we've worked out any missing steps.

**Pull request merged**
